[package]
name = "typey_birb"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.6", features = ["jpeg", "vorbis"] }
rand = "0.8"
bevy-inspector-egui = { version = "0.9", optional = true }
bevy_asset_loader = "0.9"

[patch.crates-io]
bevy = { git = "https://github.com/rparrett/bevy", branch="bevyjam1" }