[package]
name = "first_bevy_jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.6", features = ["jpeg"] }
rand = "0.8"
bevy-inspector-egui = { version = "0.8", optional = true }
bevy_asset_loader = "0.9"